[profile.default]
fs_permissions = [{ access = "read-write", path = "./"}]

[fmt]
line_length = 90
tab_width = 4
bracket_spacing = true
int_types = "long"
func_attrs_with_params_multiline = true
quote_style = "double"
number_underscore = "thousands"